### ISSUE TITLE
Command failed: Unrecognized input file format --- perhaps you need -targa

### ISSUE THREAD

**Issue by elennaro** [tableflip/mozjpeg-stream#2]
``` javaScript
req.busboy.on('file', function (fieldname, file, filename, encoding, mimetype) {

    gm(file, dirname + '/' + filename)
                        .resize(200, 200)
                        .stream('png')
                        .on('error', function (err) {
                            sails.log.error("error in input stream ", err);
                            return res.negotiate(err);
                        }).on('end', function (end) {
                                ApiService.standardJsonResponse(err, menus && menus[0], req, res);
                            });
                        })
                        .pipe(mozjpeg({ quality: jpgQuality }))
                        .pipe(fs.createWriteStream(saveTo));
            }

        });
.....
```

Fires error:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Command failed: Unrecognized input file format --- perhaps you need -targa

  at ChildProcess.onExit (****\node_modules\duplex-child-process\index.js:116:12)
  at ChildProcess.g (events.js:260:16)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at maybeClose (internal/child_process.js:818:16)
  at Socket.<anonymous> (internal/child_process.js:319:11)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at Pipe._onclose (net.js:469:12)
```

**Comment by elennaro** [comment]
It supports only JPG as input.

`.stream('png')` must be `stream('jpg')`.

Sorry to bother you and thank for nice lib!
